@startuml
actor "Bob : User" as Bob
actor "Alice : User" as Alice
participant "node0 : WWebserver" as node0
participant ": WeatherAPI" as anonymusWeatherAPI1
Bob -> node0: getWeather(location='Augsburg')
node0 -> anonymusWeatherAPI1: getWeatherData(long=48.360455, lat=10.901283)
node0 <<-- anonymusWeatherAPI1: getWeatherData: 'sunny'
Bob <<-- node0: getWeather: 'sunny'
Alice -> node0: getWeather(location='Augsburg')
node0 -> anonymusWeatherAPI1: getWeatherData(long=48.360455, lat=10.901283)
node0 <<-- anonymusWeatherAPI1: getWeatherData: 'sunny'
Alice <<-- node0: getWeather: 'sunny'
@enduml