@startuml

title Weather API

actor " Bob : User " as bob
participant "node0 : WWebserver" as node0
participant ": WeatherAPI" as weatherapi
participant " Alice : User " as Alice

bob -> node0: getWeather(location='Augsburg')
node0 -> weatherapi: getWeatherData(long=48.360455, lat=10.901283)
node0 <<-- weatherapi: getWeatherData : 'sunny'
bob <<-- node0: test = getWeather(out : 10) : 'sunny'

Alice -> node0: getWeather(location='Munich')
node0 -> weatherapi: getWeatherData(long=48.000000, lat=10.000000)
node0 <<-- weatherapi: getWeatherData : 'rain'
Alice <<-- node0: test = getWeather : 'rain'

@enduml