/*
 * generated by Xtext 2.25.0
 */
package elite.mdd.plantuml.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class PlantUMLUiModule extends AbstractPlantUMLUiModule {

	public PlantUMLUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
