/*
 * generated by Xtext 2.25.0
 */
package elite.mdd.plantuml;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class PlantUMLStandaloneSetup extends PlantUMLStandaloneSetupGenerated {

	public static void doSetup() {
		new PlantUMLStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
