/**
 * generated by Xtext 2.25.0
 */
package elite.mdd.plantuml.ui.quickfix;

import elite.mdd.plantuml.plantUML.Participant;
import elite.mdd.plantuml.validation.PlantUMLValidator;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.ui.editor.model.edit.IModificationContext;
import org.eclipse.xtext.ui.editor.model.edit.ISemanticModification;
import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;
import org.eclipse.xtext.ui.editor.quickfix.Fix;
import org.eclipse.xtext.ui.editor.quickfix.IssueResolutionAcceptor;
import org.eclipse.xtext.validation.Issue;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class PlantUMLQuickfixProvider extends DefaultQuickfixProvider {
  /* @Fix(PlantUMLValidator.class./* name is null */)
   */public void addNameToParticipant(final Issue issue, final IssueResolutionAcceptor acceptor) {
    String _get = issue.getData()[0];
    String _plus = ("Add name to participant: " + _get);
    final ISemanticModification _function = (EObject element, IModificationContext context) -> {
      final Participant participant = ((Participant) element);
      participant.setLabel(participant.getName());
      participant.setName(participant.getLabel().toLowerCase());
    };
    acceptor.accept(issue, 
      "Add name to participant", _plus, 
      "Entity.gif", _function);
  }
}
