/*
 * generated by Xtext 2.25.0
 */
package elite.mdd.plantuml.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import elite.mdd.plantuml.ide.contentassist.antlr.internal.InternalPlantUMLParser;
import elite.mdd.plantuml.services.PlantUMLGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class PlantUMLParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(PlantUMLGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, PlantUMLGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getSequenceElementAccess().getAlternatives(), "rule__SequenceElement__Alternatives");
			builder.put(grammarAccess.getParticipantAccess().getAlternatives(), "rule__Participant__Alternatives");
			builder.put(grammarAccess.getMessageDefinitionAccess().getAlternatives(), "rule__MessageDefinition__Alternatives");
			builder.put(grammarAccess.getRequestMessageDefinitionAccess().getAlternatives(), "rule__RequestMessageDefinition__Alternatives");
			builder.put(grammarAccess.getReplyMessageDefinitionAccess().getAlternatives(), "rule__ReplyMessageDefinition__Alternatives");
			builder.put(grammarAccess.getRequestMessageArgumentAccess().getAlternatives(), "rule__RequestMessageArgument__Alternatives");
			builder.put(grammarAccess.getReplyMessageAccess().getAlternatives(), "rule__ReplyMessage__Alternatives");
			builder.put(grammarAccess.getReplyMessageArgumentAccess().getAlternatives(), "rule__ReplyMessageArgument__Alternatives");
			builder.put(grammarAccess.getValueAccess().getAlternatives(), "rule__Value__Alternatives");
			builder.put(grammarAccess.getParticipantShapeAccess().getAlternatives(), "rule__ParticipantShape__Alternatives");
			builder.put(grammarAccess.getRequestArrowAccess().getAlternatives(), "rule__RequestArrow__Alternatives");
			builder.put(grammarAccess.getRightRequestAccess().getAlternatives(), "rule__RightRequest__Alternatives");
			builder.put(grammarAccess.getLeftRequestAccess().getAlternatives(), "rule__LeftRequest__Alternatives");
			builder.put(grammarAccess.getReplyArrowAccess().getAlternatives(), "rule__ReplyArrow__Alternatives");
			builder.put(grammarAccess.getDiagramAccess().getGroup(), "rule__Diagram__Group__0");
			builder.put(grammarAccess.getParticipantDefinitionAccess().getGroup(), "rule__ParticipantDefinition__Group__0");
			builder.put(grammarAccess.getParticipantAccess().getGroup_0(), "rule__Participant__Group_0__0");
			builder.put(grammarAccess.getParticipantAccess().getGroup_0_1(), "rule__Participant__Group_0_1__0");
			builder.put(grammarAccess.getParticipantAccess().getGroup_0_2(), "rule__Participant__Group_0_2__0");
			builder.put(grammarAccess.getParticipantAccess().getGroup_0_3(), "rule__Participant__Group_0_3__0");
			builder.put(grammarAccess.getParticipantAccess().getGroup_1(), "rule__Participant__Group_1__0");
			builder.put(grammarAccess.getParticipantAccess().getGroup_1_1(), "rule__Participant__Group_1_1__0");
			builder.put(grammarAccess.getParticipantAccess().getGroup_1_2(), "rule__Participant__Group_1_2__0");
			builder.put(grammarAccess.getParticipantAccess().getGroup_1_3(), "rule__Participant__Group_1_3__0");
			builder.put(grammarAccess.getRequestMessageDefinitionAccess().getGroup_0(), "rule__RequestMessageDefinition__Group_0__0");
			builder.put(grammarAccess.getRequestMessageDefinitionAccess().getGroup_0_0(), "rule__RequestMessageDefinition__Group_0_0__0");
			builder.put(grammarAccess.getRequestMessageDefinitionAccess().getGroup_0_1(), "rule__RequestMessageDefinition__Group_0_1__0");
			builder.put(grammarAccess.getRequestMessageDefinitionAccess().getGroup_1(), "rule__RequestMessageDefinition__Group_1__0");
			builder.put(grammarAccess.getRequestMessageDefinitionAccess().getGroup_1_0(), "rule__RequestMessageDefinition__Group_1_0__0");
			builder.put(grammarAccess.getRequestMessageDefinitionAccess().getGroup_1_1(), "rule__RequestMessageDefinition__Group_1_1__0");
			builder.put(grammarAccess.getReplyMessageDefinitionAccess().getGroup_0(), "rule__ReplyMessageDefinition__Group_0__0");
			builder.put(grammarAccess.getReplyMessageDefinitionAccess().getGroup_0_0(), "rule__ReplyMessageDefinition__Group_0_0__0");
			builder.put(grammarAccess.getReplyMessageDefinitionAccess().getGroup_0_1(), "rule__ReplyMessageDefinition__Group_0_1__0");
			builder.put(grammarAccess.getReplyMessageDefinitionAccess().getGroup_1(), "rule__ReplyMessageDefinition__Group_1__0");
			builder.put(grammarAccess.getReplyMessageDefinitionAccess().getGroup_1_0(), "rule__ReplyMessageDefinition__Group_1_0__0");
			builder.put(grammarAccess.getReplyMessageDefinitionAccess().getGroup_1_1(), "rule__ReplyMessageDefinition__Group_1_1__0");
			builder.put(grammarAccess.getRequestMessageAccess().getGroup(), "rule__RequestMessage__Group__0");
			builder.put(grammarAccess.getRequestMessageAccess().getGroup_1(), "rule__RequestMessage__Group_1__0");
			builder.put(grammarAccess.getRequestMessageAccess().getGroup_1_1(), "rule__RequestMessage__Group_1_1__0");
			builder.put(grammarAccess.getRequestMessageAccess().getGroup_1_1_1(), "rule__RequestMessage__Group_1_1_1__0");
			builder.put(grammarAccess.getRequestMessageArgumentAccess().getGroup_0(), "rule__RequestMessageArgument__Group_0__0");
			builder.put(grammarAccess.getRequestMessageArgumentAccess().getGroup_1(), "rule__RequestMessageArgument__Group_1__0");
			builder.put(grammarAccess.getRequestMessageArgumentAccess().getGroup_2(), "rule__RequestMessageArgument__Group_2__0");
			builder.put(grammarAccess.getReplyMessageAccess().getGroup_0(), "rule__ReplyMessage__Group_0__0");
			builder.put(grammarAccess.getReplyMessageAccess().getGroup_1(), "rule__ReplyMessage__Group_1__0");
			builder.put(grammarAccess.getReplyMessageAccess().getGroup_2(), "rule__ReplyMessage__Group_2__0");
			builder.put(grammarAccess.getReplyMessageAccess().getGroup_2_1(), "rule__ReplyMessage__Group_2_1__0");
			builder.put(grammarAccess.getReplyMessageAccess().getGroup_2_1_1(), "rule__ReplyMessage__Group_2_1_1__0");
			builder.put(grammarAccess.getReplyMessageAccess().getGroup_2_1_1_1(), "rule__ReplyMessage__Group_2_1_1_1__0");
			builder.put(grammarAccess.getReplyMessageAccess().getGroup_3(), "rule__ReplyMessage__Group_3__0");
			builder.put(grammarAccess.getReplyMessageAccess().getGroup_3_3(), "rule__ReplyMessage__Group_3_3__0");
			builder.put(grammarAccess.getReplyMessageAccess().getGroup_3_3_1(), "rule__ReplyMessage__Group_3_3_1__0");
			builder.put(grammarAccess.getReplyMessageAccess().getGroup_3_3_1_1(), "rule__ReplyMessage__Group_3_3_1_1__0");
			builder.put(grammarAccess.getReplyMessageAccess().getGroup_3_4(), "rule__ReplyMessage__Group_3_4__0");
			builder.put(grammarAccess.getReplyMessageArgumentAccess().getGroup_0(), "rule__ReplyMessageArgument__Group_0__0");
			builder.put(grammarAccess.getReplyMessageArgumentAccess().getGroup_1(), "rule__ReplyMessageArgument__Group_1__0");
			builder.put(grammarAccess.getReplyMessageArgumentAccess().getGroup_2(), "rule__ReplyMessageArgument__Group_2__0");
			builder.put(grammarAccess.getReplyMessageArgumentAccess().getGroup_3(), "rule__ReplyMessageArgument__Group_3__0");
			builder.put(grammarAccess.getDiagramAccess().getElementsAssignment_1(), "rule__Diagram__ElementsAssignment_1");
			builder.put(grammarAccess.getParticipantDefinitionAccess().getShapeAssignment_0(), "rule__ParticipantDefinition__ShapeAssignment_0");
			builder.put(grammarAccess.getParticipantDefinitionAccess().getParticipantAssignment_1(), "rule__ParticipantDefinition__ParticipantAssignment_1");
			builder.put(grammarAccess.getParticipantAccess().getLabelAssignment_0_0(), "rule__Participant__LabelAssignment_0_0");
			builder.put(grammarAccess.getParticipantAccess().getSelectorAssignment_0_1_1(), "rule__Participant__SelectorAssignment_0_1_1");
			builder.put(grammarAccess.getParticipantAccess().getTypeAssignment_0_2_1(), "rule__Participant__TypeAssignment_0_2_1");
			builder.put(grammarAccess.getParticipantAccess().getInteractionIdentAssignment_0_3_1(), "rule__Participant__InteractionIdentAssignment_0_3_1");
			builder.put(grammarAccess.getParticipantAccess().getNameAssignment_0_5(), "rule__Participant__NameAssignment_0_5");
			builder.put(grammarAccess.getParticipantAccess().getNameAssignment_1_0(), "rule__Participant__NameAssignment_1_0");
			builder.put(grammarAccess.getParticipantAccess().getSelectorAssignment_1_1_1(), "rule__Participant__SelectorAssignment_1_1_1");
			builder.put(grammarAccess.getParticipantAccess().getTypeAssignment_1_2_1(), "rule__Participant__TypeAssignment_1_2_1");
			builder.put(grammarAccess.getParticipantAccess().getInteractionIdentAssignment_1_3_1(), "rule__Participant__InteractionIdentAssignment_1_3_1");
			builder.put(grammarAccess.getRequestMessageDefinitionAccess().getSenderAssignment_0_0_1(), "rule__RequestMessageDefinition__SenderAssignment_0_0_1");
			builder.put(grammarAccess.getRequestMessageDefinitionAccess().getArrowAssignment_0_0_3(), "rule__RequestMessageDefinition__ArrowAssignment_0_0_3");
			builder.put(grammarAccess.getRequestMessageDefinitionAccess().getReceiverAssignment_0_0_5(), "rule__RequestMessageDefinition__ReceiverAssignment_0_0_5");
			builder.put(grammarAccess.getRequestMessageDefinitionAccess().getMessageAssignment_0_1_1(), "rule__RequestMessageDefinition__MessageAssignment_0_1_1");
			builder.put(grammarAccess.getRequestMessageDefinitionAccess().getReceiverAssignment_1_0_1(), "rule__RequestMessageDefinition__ReceiverAssignment_1_0_1");
			builder.put(grammarAccess.getRequestMessageDefinitionAccess().getArrowAssignment_1_0_3(), "rule__RequestMessageDefinition__ArrowAssignment_1_0_3");
			builder.put(grammarAccess.getRequestMessageDefinitionAccess().getSenderAssignment_1_0_5(), "rule__RequestMessageDefinition__SenderAssignment_1_0_5");
			builder.put(grammarAccess.getRequestMessageDefinitionAccess().getMessageAssignment_1_1_1(), "rule__RequestMessageDefinition__MessageAssignment_1_1_1");
			builder.put(grammarAccess.getReplyMessageDefinitionAccess().getSenderAssignment_0_0_1(), "rule__ReplyMessageDefinition__SenderAssignment_0_0_1");
			builder.put(grammarAccess.getReplyMessageDefinitionAccess().getArrowAssignment_0_0_3(), "rule__ReplyMessageDefinition__ArrowAssignment_0_0_3");
			builder.put(grammarAccess.getReplyMessageDefinitionAccess().getReceiverAssignment_0_0_5(), "rule__ReplyMessageDefinition__ReceiverAssignment_0_0_5");
			builder.put(grammarAccess.getReplyMessageDefinitionAccess().getMessageAssignment_0_1_1(), "rule__ReplyMessageDefinition__MessageAssignment_0_1_1");
			builder.put(grammarAccess.getReplyMessageDefinitionAccess().getReceiverAssignment_1_0_1(), "rule__ReplyMessageDefinition__ReceiverAssignment_1_0_1");
			builder.put(grammarAccess.getReplyMessageDefinitionAccess().getArrowAssignment_1_0_3(), "rule__ReplyMessageDefinition__ArrowAssignment_1_0_3");
			builder.put(grammarAccess.getReplyMessageDefinitionAccess().getSenderAssignment_1_0_5(), "rule__ReplyMessageDefinition__SenderAssignment_1_0_5");
			builder.put(grammarAccess.getReplyMessageDefinitionAccess().getMessageAssignment_1_1_1(), "rule__ReplyMessageDefinition__MessageAssignment_1_1_1");
			builder.put(grammarAccess.getRequestMessageAccess().getNameAssignment_0(), "rule__RequestMessage__NameAssignment_0");
			builder.put(grammarAccess.getRequestMessageAccess().getArgumentsAssignment_1_1_0(), "rule__RequestMessage__ArgumentsAssignment_1_1_0");
			builder.put(grammarAccess.getRequestMessageAccess().getArgumentsAssignment_1_1_1_1(), "rule__RequestMessage__ArgumentsAssignment_1_1_1_1");
			builder.put(grammarAccess.getRequestMessageArgumentAccess().getNameAssignment_2_0(), "rule__RequestMessageArgument__NameAssignment_2_0");
			builder.put(grammarAccess.getRequestMessageArgumentAccess().getValueAssignment_2_2(), "rule__RequestMessageArgument__ValueAssignment_2_2");
			builder.put(grammarAccess.getReplyMessageAccess().getNameAssignment_2_0(), "rule__ReplyMessage__NameAssignment_2_0");
			builder.put(grammarAccess.getReplyMessageAccess().getArgumentsAssignment_2_1_1_0(), "rule__ReplyMessage__ArgumentsAssignment_2_1_1_0");
			builder.put(grammarAccess.getReplyMessageAccess().getArgumentsAssignment_2_1_1_1_1(), "rule__ReplyMessage__ArgumentsAssignment_2_1_1_1_1");
			builder.put(grammarAccess.getReplyMessageAccess().getVariableAssignment_3_0(), "rule__ReplyMessage__VariableAssignment_3_0");
			builder.put(grammarAccess.getReplyMessageAccess().getNameAssignment_3_2(), "rule__ReplyMessage__NameAssignment_3_2");
			builder.put(grammarAccess.getReplyMessageAccess().getArgumentsAssignment_3_3_1_0(), "rule__ReplyMessage__ArgumentsAssignment_3_3_1_0");
			builder.put(grammarAccess.getReplyMessageAccess().getArgumentsAssignment_3_3_1_1_1(), "rule__ReplyMessage__ArgumentsAssignment_3_3_1_1_1");
			builder.put(grammarAccess.getReplyMessageAccess().getValueAssignment_3_4_1(), "rule__ReplyMessage__ValueAssignment_3_4_1");
			builder.put(grammarAccess.getReplyMessageArgumentAccess().getNameAssignment_2_0(), "rule__ReplyMessageArgument__NameAssignment_2_0");
			builder.put(grammarAccess.getReplyMessageArgumentAccess().getValueAssignment_2_2(), "rule__ReplyMessageArgument__ValueAssignment_2_2");
			builder.put(grammarAccess.getReplyMessageArgumentAccess().getNameAssignment_3_0(), "rule__ReplyMessageArgument__NameAssignment_3_0");
			builder.put(grammarAccess.getReplyMessageArgumentAccess().getOutParamAssignment_3_2(), "rule__ReplyMessageArgument__OutParamAssignment_3_2");
			builder.put(grammarAccess.getReplyMessageArgumentAccess().getValueAssignment_3_4(), "rule__ReplyMessageArgument__ValueAssignment_3_4");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private PlantUMLGrammarAccess grammarAccess;

	@Override
	protected InternalPlantUMLParser createParser() {
		InternalPlantUMLParser result = new InternalPlantUMLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public PlantUMLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(PlantUMLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
