/*
 * generated by Xtext 2.25.0
 */
package elite.mdd.plantuml.ui;

import com.google.inject.Injector;
import elite.mdd.plantuml.ui.internal.PlantumlActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PlantUMLExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(PlantumlActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		PlantumlActivator activator = PlantumlActivator.getInstance();
		return activator != null ? activator.getInjector(PlantumlActivator.ELITE_MDD_PLANTUML_PLANTUML) : null;
	}

}
