/*
 * generated by Xtext 2.25.0
 */
package elite.mdd.plantuml.validation

import org.eclipse.xtext.validation.Check
import elite.mdd.plantuml.plantUML.Participant
import elite.mdd.plantuml.plantUML.PlantUMLPackage

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class PlantUMLValidator extends AbstractPlantUMLValidator {
	
	protected static val ISSUE_CODE_PREFIX = "elite.mdd.plantuml."
	
	public static val PARTICIPANT_NAME_MISSING = 
		ISSUE_CODE_PREFIX + "ParticipantNameMissing"
	
	
	@Check
	def checkNoName(Participant participant) {
		if (participant.label !== null) {
			return
		}
		warning("Participant " + participant.name + " should have an explicit name",
			PlantUMLPackage.eINSTANCE.participant_Label,
			PARTICIPANT_NAME_MISSING,
			participant.name
		)
	}
	
//	public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					PlantUMLPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}
	
}
