/*
 * generated by Xtext 2.25.0
 */
package elite.mdd.plantuml.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import elite.mdd.plantuml.PlantUMLRuntimeModule;
import elite.mdd.plantuml.PlantUMLStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class PlantUMLIdeSetup extends PlantUMLStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new PlantUMLRuntimeModule(), new PlantUMLIdeModule()));
	}
	
}
