/*
 * generated by Xtext 2.25.0
 */
package elite.mdd.plantuml.formatting2;

import elite.mdd.plantuml.plantUML.Diagram;
import elite.mdd.plantuml.plantUML.ParticipantDefinition;
import elite.mdd.plantuml.plantUML.SequenceElement;
import org.eclipse.xtext.formatting2.AbstractJavaFormatter;
import org.eclipse.xtext.formatting2.IFormattableDocument;

public class PlantUMLFormatter extends AbstractJavaFormatter {

	protected void format(Diagram diagram, IFormattableDocument doc) {
		for (SequenceElement sequenceElement : diagram.getElements()) {
			doc.format(sequenceElement);
			doc.prepend(sequenceElement, this::newLine);
			doc.append(sequenceElement, this::newLine);
		}
	}

	protected void format(ParticipantDefinition participantDefinition, IFormattableDocument doc) {
		// TODO: format HiddenRegions around keywords, attributes, cross references, etc. 
		doc.format(participantDefinition.getParticipant());
	}
	
	// TODO: implement for RequestMessageDefinition, ReplyMessageDefinition, RequestMessage, RequestMessageArgument, ReplyMessage, ReplyMessageArgument
}
